services:
  flyway-repair:
    image: flyway/flyway:10-alpine
    command: -url=jdbc:postgresql://db:5432/kanban -user=kanban -password=kanban repair
    depends_on:
      db:
        condition: service_healthy
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kanban
      - SPRING_DATASOURCE_USERNAME=kanban
      - SPRING_DATASOURCE_PASSWORD=kanban
      - JWT_SECRET=LongSecureRandomSecretForJWTAuthentication2025
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
      - POSTGRES_DB=kanban
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: